services:
  quantize-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantize-gpu
    privileged: true
    profiles:
      - quantize-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - NCCL_DEBUG=INFO
      # - NCCL_TIMEOUT=300
      # - TORCH_NCCL_TRACE_BUFFER_SIZE=16384
      # - NCCL_ASYNC_ERROR_HANDLING=1
      # - TORCH_DISTRIBUTED_DEBUG=DETAIL
      - NCCL_DEBUG=INFO
      - NCCL_P2P_DISABLE=1 # Sirius no communication between GPUs
    volumes:
      - ./:/workspace
      # - /data3/rogelio:/workspace/data3
    stdin_open: true
    tty: true
    command: /bin/bash -c "tail -f /dev/null"
    network_mode: "host"
    shm_size: 32g # At least 4GB per GPU process
  
  quantize-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantize-cpu
    privileged: true
    profiles:
      - quantize-cpu
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
    command: /bin/bash -c "tail -f /dev/null"
    network_mode: "host"
    shm_size: 32g

# docker-compose --profile quantize-gpu up --build -d
# docker-compose --profile quantize-cpu up --build -d