action: load # resume
train_id: null
dataset_name: imagenet
model: pytorchcv_preresnet18 # pytorchcv_vitb16
nepochs: 2 # 300
batch_size: 128
optimizer: SGD
momentum: 0.9
nesterov: False
weight_norm: null
lr_scheduler: LinearWarmupCosineAnnealing
warmup_epochs: 10
warmup_lr: 0.00001

nworkers: 4
# Quantizer Settings
w_first_last_quantizer: null
x_first_last_quantizer: null
w_first_last_initializer: null
x_first_last_initializer: null
w_first_last_grad_scale_mode: null
x_first_last_grad_scale_mode: null
first_bits: 8
last_bits: 8
init_num: 100
w_initializer: null
x_initializer: null
w_quantizer: null
x_qnautizer: null
w_grad_scale_mode: null
x_grad_scale_mode: null
# Qparms Optimizer settings
different_optimizer_mode: True
step_size_optimizer: AdamW
pre_trained: False
evaluation_mode: True
write_log: True
ddp: False
invisible_pgb: False
save_path: output
save_mode: all_checkpoints