# python main.py --mode QAT --num_bits 2 --lr 0.1 --weight_decay 1e-4 --x_quantizer LSQ_quantizer --w_quantizer LSQ_quantizer --initializer LSQ_initializer
action: load # resume
train_id: null
dataset_name: co3d
model: vggt
nepochs: 300
batch_size: 32
optimizer: SGD
momentum: 0.9
nesterov: False
weight_norm: null
lr_scheduler: LinearWarmupCosineAnnealing
warmup_epochs: 20
warmup_lr: 0.00001

nworkers: 10
# Quantizer Settings
w_first_last_quantizer: null
x_first_last_quantizer: null
w_first_last_initializer: null
x_first_last_initializer: null
w_first_last_grad_scale_mode: null
x_first_last_grad_scale_mode: null
first_bits: 16
last_bits: 16
init_num: 100
w_initializer: null
x_initializer: null
w_quantizer: null
x_quantizer: null
w_grad_scale_mode: null
x_grad_scale_mode: null
# Qparms Optimizer settings
different_optimizer_mode: True
step_size_optimizer: AdamW
pre_trained: True
evaluation_mode: True
write_log: True
ddp: False
gpu_rank: 1 # Can be multiple ranks: 0,1
invisible_pgb: False
save_path: output
save_mode: xxxall_checkpoints